# Generated by Django 3.0.3 on 2020-02-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('kind', models.CharField(choices=[('senior', '研究生'), ('junior', '本科生'), ('Teacher', '教师')], default='研究生', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
    ]
